export var basicConstant = {
  VIEWSTATE_NEW: 'NEW',
  VIEWSTATE_VIEW: 'VIEW',
  VIEWSTATE_MODIFY: 'MODIFY',

  // FORMTYPE_DETAIL: 'DETAIL',
  // FORMTYPE_LIST: 'LIST',
  // FORMTYPE_SELECT:'SELECT',
  // FORMTYPE_COMMAND:'COMMOND',

  DEPENDENCE_VALUE: 'VALUE',
  DEPENDENCE_ENABLE: 'ENABLE',
  DEPENDENCE_EDITABLE: 'EDITABLE',
  DEPENDENCE_READONLY: 'READONLY',
  DEPENDENCE_REQUIRED: 'REQUIRED',
  DEPENDENCE_UNIQUE: 'UNIQUE',
  DEPENDENCE_HIDDEN: 'HIDDEN'
}
