export var basicConstant = {
  VIEWSTATE_NEW: 'NEW',
  VIEWSTATE_VIEW: 'VIEW',
  VIEWSTATE_MODIFY: 'MODIFY',

  FORMTYPE_FORM: 'FORM',
  FORMTYPE_BASE: 'BASEFORM',
  FORMTYPE_LIST: 'LISTFORM',
  FORMTYPE_SELECT: 'SELECTFORM',
  FORMTYPE_COMMAND: 'COMMONDFORM',
  FORMTYPE_DETAIL: 'DETAILFORM',

  CMP_COMPONENTSET: 'COMPONENTSET',
  CMP_TOOLBAR: 'TOOLBAR',
  CMP_BUTTON: 'BUTTON',
  CMP_PANEL: 'PANEL'
  // DEPENDENCE_VALUE: 'VALUE',
  // DEPENDENCE_ENABLE: 'ENABLE',
  // DEPENDENCE_EDITABLE: 'EDITABLE',
  // DEPENDENCE_READONLY: 'READONLY',
  // DEPENDENCE_REQUIRED: 'REQUIRED',
  // DEPENDENCE_UNIQUE: 'UNIQUE',
  // DEPENDENCE_HIDDEN: 'HIDDEN'
}
